"""项目业务规则默认值。"""

DEFAULT_FIELD_OFFSET_THRESHOLD_M = 5.0
DEFAULT_FIELD_SEARCH_RADIUS_M = 1000.0
DEFAULT_POSITIONAL_ACCURACY_PIXELS = 2.0
DEFAULT_MAX_CAPTURE_IMAGE_DAYS = 15
DEFAULT_CONSTRUCTION_MIN_AREA_SQM = 200.0
DEFAULT_OTHER_AGRICULTURAL_MIN_AREA_SQM = 400.0
DEFAULT_COMPLETENESS_RATE_MIN = 98.0
DEFAULT_BOUNDARY_AGREEMENT_RATE_MIN = 90.0
DEFAULT_LAND_CLASS_ACCURACY_MIN = 90.0
DEFAULT_KEY_FIELD_ACCURACY_MIN = 95.0
DEFAULT_MAX_CLOUD_COVER_PERCENT = None
DEFAULT_OUTPUT_CRS = "EPSG:4490"
DEFAULT_OUTPUT_PROJECTION = "CGCS2000 高斯-克吕格（按成果分幅配置中央经线）"
DEFAULT_RULE_OPERATOR = "系统默认配置"
